name: flowpyenv
channels:
  - conda-forge
dependencies:
  - meson
  - fmt
  - pkg-config
  - cmake
  - ninja 
  - cpp-argparse
  - clang-format=18.1.1
  - tomlplusplus
  - catch2
  - xtensor 
  - xtensor-blas
  - xtensor-python
  - python
  - pybind11